# Generated by Django 3.2.6 on 2021-08-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDtls',
        ),
    ]
