# Generated by Django 3.2.6 on 2021-08-19 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdtls',
            name='groups',
        ),
        migrations.AlterField(
            model_name='userdtls',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
