# Generated by Django 3.2.6 on 2021-08-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('profile_page', '0003_auto_20210819_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassChange',
        ),
    ]
