# Generated by Django 3.2.6 on 2021-08-28 23:10

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColourPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('colour', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
    ]
