# Generated by Django 3.2.6 on 2021-08-20 20:38

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourMix_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColourPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.DeleteModel(
            name='ColorModel',
        ),
    ]
