# Generated by Django 3.2.6 on 2021-08-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourMix_page', '0002_auto_20210820_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='colourpic',
            name='volume',
            field=models.IntegerField(default='default'),
            preserve_default=False,
        ),
    ]
