# Generated by Django 3.2.6 on 2021-09-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colourMix_page', '0002_colourcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='colourcatalog',
            name='hex',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
